name: 'Check Bundle Size'
description: 'Check Bundle size action for monorepos'
author: 'sandinosaso'
inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true
  command_for_building:
    description: The command to build your project
    required: true
    default: 'yarn build'
  debug_command:
    description: The command to debug_command 
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'