name: 'Check Bundle Size'
description: 'Check Bundle size action for monorepos'
author: 'sandinosaso'
inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true
  stats_file_path:
    description: The path to the stats.json file
    required: true
    default: 'dist/stats.json'
runs:
  using: 'node12'
  main: 'dist/index.js'